# Generated by Django 4.1.5 on 2023-02-06 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('index', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date_mutation', models.CharField(max_length=255)),
                ('Annee_mutation', models.CharField(max_length=255)),
                ('Nature_mutation', models.CharField(max_length=255)),
                ('Valeur_fonciere', models.CharField(max_length=255)),
                ('Type_local', models.CharField(max_length=255)),
                ('Price_square_meter', models.CharField(max_length=255)),
                ('Nombre_pieces_principales', models.CharField(max_length=255)),
                ('Surface_reelle_bati', models.CharField(max_length=255)),
                ('Surface_terrain', models.CharField(max_length=255)),
                ('No_voie', models.CharField(max_length=255)),
                ('Voie', models.CharField(max_length=255)),
                ('Code_postal', models.CharField(max_length=255)),
            ],
        ),
    ]
