# Generated by Django 4.1.5 on 2023-02-07 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('immodata', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='index',
            new_name='id',
        ),
    ]
